
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: